meta_product_name: "Snuffd"
meta_title: "Snuffd | Safe is sexy"
meta_description: "Save your sexual health results, track treatments and share results with others."
meta_image: "snuffd_hero.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
